### ISSUE TITLE
Copyright & License

### ISSUE THREAD

**Issue by jkobti** [CycloneDX/cyclonedx-ruby-gem#1]
I have a question about Copyright & License!
I have already created a gem that is working, should I include the Copyright & License notice at the head of each file, or should I simply create a PR with the code I have and then we'll add that stuff later on before we merge it?
I'm not really familiar how this stuff work

**Comment by stevespringett** [comment]
Thanks for working on this. In general, the more information you're able to capture (accurately), the more factual (and useful) the BOM will be. Copyright, publisher, etc are all good to have. One thing that's critical to have is purl. Let me know if you have questions on purl.

CycloneDX schema v1.1 will be launched on March 1. The schema is backward compatible, but there are enhancements to license which may or may not affect gems.

All CycloneDX implementations will eventually need to be updated to be able to support schema v1.0 and v1.1. The current DRAFT-3 is available here: https://github.com/CycloneDX/specification/blob/master/schema/bom-1.1-DRAFT-3.xsd I'm currently in the process of writing test cases for it. I don't anticipate any major changes between now and release. Perhaps a few tweaks (if any).

This is a summary of the enhancements made to license:

- The `<licenses>` node can now contain a choice between a list of `<license>` or an SPDX `<expression>`
- A `<license>` node may now contain the full `<text>` of the license along with attributes for the content-type and encoding. 
- A `<license>` node may now contain an external `<url>` to the license.

There is also the concept of `<externalReferences>` which allows describing various things like issue tracker, docs, vcs, etc.

I'd recommend submitting a PR that supports schema 1.0 - we can iterate on it if necessary. We can plan for schema 1.1 support in March/April.

FYI: Dependency-Track doesn't support schema 1.1 - but will have partial support for it in 3.5 with full support being added in later releases.
